# Yambda 50M likes — CDN-style Two-Tower baseline

## 0. Imports and config

In [1]:
import os
import json
import random
import itertools
import gc
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
import polars as pl

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm import tqdm


def set_seed(seed: int = 0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


CFG = {
    # Paths
    "data_dir": "../data",
    "interactions_file": "likes.parquet",
    "artist_file": "artist_item_mapping.parquet",
    "album_file": "album_item_mapping.parquet",

    # Debug/data filtering
    # None = all users; for debugging set 50_000 or 100_000
    "max_users": None,
    "min_user_interactions": 3,
    "min_item_interactions": 5,

    # Model
    "embed_dim": 64,
    "artist_emb_dim": 32,
    "album_emb_dim": 32,
    "tower_hidden": [256, 128, 64],
    "dropout": 0.0,

    # Training
    "batch_size": 4096,
    "grad_clip": 1.0,
    "lr": 1e-3,
    "weight_decay": 0.0,

    # Grid search
    "tune_fast": True,
    "tune_epochs": 3,
    "tune_val_fraction": 1.00,
    "skip_tune_if_cached": True,
    "cache_path": "best_hparams_yambda_likes_features.json",

    # Final training
    "final_epochs": 20,

    # Evaluation
    "eval_k": [10, 50],
    "eval_batch_users": 128,
    "eval_item_batch": 8192,
    "head_fraction": 0.20,

    # Reproducibility
    "seed": 0,
    "seeds": [0, 1, 2, 3, 4],
}

set_seed(CFG["seed"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)
print(f"Final: {len(CFG['seeds'])} seed(s) × {CFG['final_epochs']} epochs")

device: cuda
Final: 5 seed(s) × 20 epochs

## 1. Load data

In [2]:
def find_file(data_dir: str | Path, name: str) -> Path:
    data_dir = Path(data_dir)
    candidates = [
        data_dir / name,
        data_dir / f"{name}.parquet",
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError(f"Could not find {name}. Tried: {candidates}")


def normalize_interaction_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"uid", "user_id", "userid", "user"}:
            rename[c] = "uid"
        elif lc in {"item_id", "itemid", "track_id", "trackid", "song_id"}:
            rename[c] = "item_id"
        elif lc in {"timestamp", "ts", "time", "event_timestamp", "datetime"}:
            rename[c] = "timestamp"
    return df.rename(rename)


def normalize_item_side_columns(df: pl.DataFrame) -> pl.DataFrame:
    rename = {}
    for c in df.columns:
        lc = c.lower()
        if lc in {"item_id", "itemid", "track_id", "trackid"}:
            rename[c] = "item_id"
        elif lc in {"artist_id", "artistid"}:
            rename[c] = "artist_id"
        elif lc in {"album_id", "albumid"}:
            rename[c] = "album_id"
    return df.rename(rename)


DATA_DIR = Path(CFG["data_dir"])
INTERACTIONS_PATH = find_file(DATA_DIR, CFG["interactions_file"])
ARTIST_PATH = find_file(DATA_DIR, CFG["artist_file"])
ALBUM_PATH = find_file(DATA_DIR, CFG["album_file"])

print("interactions:", INTERACTIONS_PATH)
print("artists:", ARTIST_PATH)
print("albums:", ALBUM_PATH)

interactions = pl.read_parquet(INTERACTIONS_PATH)
interactions = normalize_interaction_columns(interactions)

print("raw interactions:", interactions.shape)
print("columns:", interactions.columns)
print(interactions.head())

required = {"uid", "item_id"}
missing = required - set(interactions.columns)
assert not missing, f"Missing required columns {missing}. Available: {interactions.columns}"

if "timestamp" not in interactions.columns:
    print("[WARN] timestamp not found: using row index as timestamp")
    interactions = interactions.with_row_index("timestamp")

interactions = interactions.select(["uid", "item_id", "timestamp"])

# Deduplicate repeated likes by the same user for the same item.
interactions = (
    interactions
    .sort("timestamp")
    .unique(subset=["uid", "item_id"], keep="first")
)

print("after dedup:", interactions.shape)

interactions: ../data/likes.parquet
artists: ../data/artist_item_mapping.parquet
albums: ../data/album_item_mapping.parquet
raw interactions: (881456, 4)
columns: ['uid', 'timestamp', 'item_id', 'is_organic']
shape: (5, 4)
┌─────┬───────────┬─────────┬────────────┐
│ uid ┆ timestamp ┆ item_id ┆ is_organic │
│ --- ┆ ---       ┆ ---     ┆ ---        │
│ u32 ┆ u32       ┆ u32     ┆ u8         │
╞═════╪═══════════╪═════════╪════════════╡
│ 100 ┆ 44755     ┆ 732449  ┆ 1          │
│ 100 ┆ 1155860   ┆ 6568592 ┆ 0          │
│ 100 ┆ 1259125   ┆ 5411243 ┆ 1          │
│ 100 ┆ 1260005   ┆ 7371186 ┆ 0          │
│ 100 ┆ 1263935   ┆ 4943655 ┆ 0          │
└─────┴───────────┴─────────┴────────────┘
after dedup: (844690, 3)

## 2. Filtering

In [3]:
# Item-core filter
item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
interactions = interactions.join(good_items, on="item_id", how="semi")
print("after item-core:", interactions.shape)

# User-core filter
user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
interactions = interactions.join(good_users, on="uid", how="semi")
print("after user-core:", interactions.shape)

# Optional debug subset by users. This does not break histories.
if CFG["max_users"] is not None:
    users_sub = (
        interactions
        .select("uid")
        .unique()
        .sample(n=int(CFG["max_users"]), seed=CFG["seed"])
    )
    interactions = interactions.join(users_sub, on="uid", how="semi")
    print(f"after max_users={CFG['max_users']}:", interactions.shape)

    # Repeat filters after subsampling.
    item_counts = interactions.group_by("item_id").len().rename({"len": "cnt"})
    good_items = item_counts.filter(pl.col("cnt") >= CFG["min_item_interactions"]).select("item_id")
    interactions = interactions.join(good_items, on="item_id", how="semi")

    user_counts = interactions.group_by("uid").len().rename({"len": "cnt"})
    good_users = user_counts.filter(pl.col("cnt") >= CFG["min_user_interactions"]).select("uid")
    interactions = interactions.join(good_users, on="uid", how="semi")

print("final filtered:", interactions.shape)
print("users:", interactions["uid"].n_unique())
print("items:", interactions["item_id"].n_unique())

after item-core: (621417, 3)
after user-core: (620105, 3)
final filtered: (620105, 3)
users: 7102
items: 33145

## 3. ID mapping and leave-one-out split

In [4]:
# User/item ids -> contiguous indices.
user_mapping = interactions.select("uid").unique().sort("uid").with_row_index(name="u_idx")
item_mapping = interactions.select("item_id").unique().sort("item_id").with_row_index(name="i_idx")

inter = (
    interactions
    .join(user_mapping, on="uid", how="inner")
    .join(item_mapping, on="item_id", how="inner")
    .select(["u_idx", "i_idx", "timestamp"])
    .sort(["u_idx", "timestamp"])
)

NUM_USERS = user_mapping.height
NUM_ITEMS = item_mapping.height

inter = inter.with_columns([
    pl.arange(0, pl.len()).over("u_idx").alias("pos"),
    pl.len().over("u_idx").alias("hist_len"),
])

# Leave-one-out evaluation with validation:
# most recent item -> test, second most recent -> validation, rest -> train.
train_df = inter.filter(pl.col("pos") < pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
val_df   = inter.filter(pl.col("pos") == pl.col("hist_len") - 2).select(["u_idx", "i_idx"])
test_df  = inter.filter(pl.col("pos") == pl.col("hist_len") - 1).select(["u_idx", "i_idx"])

train_pairs = train_df.to_numpy().astype(np.int64)
val_np = val_df.to_numpy().astype(np.int64)
test_np = test_df.to_numpy().astype(np.int64)

val_u, val_i = val_np[:, 0], val_np[:, 1]
test_u, test_i = test_np[:, 0], test_np[:, 1]

print(f"NUM_USERS={NUM_USERS:,}")
print(f"NUM_ITEMS={NUM_ITEMS:,}")
print(f"train={len(train_pairs):,} val={len(val_u):,} test={len(test_u):,}")
print(f"catalog share @50 = {50 / NUM_ITEMS:.6f}")

assert len(train_pairs) > 0
assert len(val_u) == NUM_USERS
assert len(test_u) == NUM_USERS

NUM_USERS=7,102
NUM_ITEMS=33,145
train=605,901 val=7,102 test=7,102
catalog share @50 = 0.001509

## 4. Build item features: artist_id and album_id

In [5]:
item_features_df = item_mapping.select(["item_id", "i_idx"])

# ---------- artist feature ----------
artists = pl.read_parquet(ARTIST_PATH)
artists = normalize_item_side_columns(artists)

print("artists shape:", artists.shape)
print("artists columns:", artists.columns)

if "item_id" not in artists.columns or "artist_id" not in artists.columns:
    raise ValueError(f"Bad artist mapping columns: {artists.columns}")

# If an item has multiple artists, take the first one for a simple baseline.
artists_one = (
    artists
    .select(["item_id", "artist_id"])
    .drop_nulls(["item_id", "artist_id"])
    .group_by("item_id")
    .agg(pl.col("artist_id").first())
)

item_features_df = item_features_df.join(artists_one, on="item_id", how="left")


# ---------- album feature ----------
albums = pl.read_parquet(ALBUM_PATH)
albums = normalize_item_side_columns(albums)

print("albums shape:", albums.shape)
print("albums columns:", albums.columns)

if "item_id" not in albums.columns or "album_id" not in albums.columns:
    raise ValueError(f"Bad album mapping columns: {albums.columns}")

# If an item has multiple albums, take the first one for a simple baseline.
albums_one = (
    albums
    .select(["item_id", "album_id"])
    .drop_nulls(["item_id", "album_id"])
    .group_by("item_id")
    .agg(pl.col("album_id").first())
)

item_features_df = item_features_df.join(albums_one, on="item_id", how="left")


# ---------- categorical encoding ----------
item_features_df = item_features_df.sort("i_idx")

# unknown = 0, real categories = 1..N
unique_artists = (
    item_features_df
    .select("artist_id")
    .drop_nulls()
    .unique()
    .sort("artist_id")
    .with_row_index(name="artist_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_artists, on="artist_id", how="left")
    .with_columns(pl.col("artist_idx").fill_null(0).cast(pl.Int64))
)

unique_albums = (
    item_features_df
    .select("album_id")
    .drop_nulls()
    .unique()
    .sort("album_id")
    .with_row_index(name="album_idx", offset=1)
)

item_features_df = (
    item_features_df
    .join(unique_albums, on="album_id", how="left")
    .with_columns(pl.col("album_idx").fill_null(0).cast(pl.Int64))
)

ITEM_ARTIST = item_features_df["artist_idx"].to_numpy().astype(np.int64)
ITEM_ALBUM = item_features_df["album_idx"].to_numpy().astype(np.int64)

NUM_ARTISTS = int(ITEM_ARTIST.max()) + 1
NUM_ALBUMS = int(ITEM_ALBUM.max()) + 1

print("NUM_ITEMS:", NUM_ITEMS)
print("NUM_ARTISTS:", NUM_ARTISTS)
print("NUM_ALBUMS:", NUM_ALBUMS)
print("artist unknown share:", float((ITEM_ARTIST == 0).mean()))
print("album unknown share:", float((ITEM_ALBUM == 0).mean()))

item_artist_t = torch.from_numpy(ITEM_ARTIST).long().to(device)
item_album_t = torch.from_numpy(ITEM_ALBUM).long().to(device)

artists shape: (9271906, 2)
artists columns: ['artist_id', 'item_id']
albums shape: (9651644, 2)
albums columns: ['album_id', 'item_id']
NUM_ITEMS: 33145
NUM_ARTISTS: 9321
NUM_ALBUMS: 23839
artist unknown share: 0.0
album unknown share: 3.017046311660884e-05

## 5. Known items and head/tail split

In [6]:
train_user_items = [set() for _ in range(NUM_USERS)]

for u, i in train_pairs:
    train_user_items[int(u)].add(int(i))

known_val = [set(s) for s in train_user_items]
known_test = [set(s) for s in train_user_items]

# For test, validation item is already known and should be masked.
for u, i in zip(val_u, val_i):
    known_test[int(u)].add(int(i))

# Head/tail is computed only from train frequencies.
item_freq = np.bincount(train_pairs[:, 1], minlength=NUM_ITEMS)
order = np.argsort(-item_freq)

n_head = max(1, int(NUM_ITEMS * CFG["head_fraction"]))
head_mask = np.zeros(NUM_ITEMS, dtype=bool)
head_mask[order[:n_head]] = True

print(f"head={head_mask.sum():,} tail={(~head_mask).sum():,}")
print(f"nonzero train items={np.sum(item_freq > 0):,}")
print(f"zero train items={np.sum(item_freq == 0):,}")
print(f"val true head share={head_mask[val_i].mean():.4f}")
print(f"test true head share={head_mask[test_i].mean():.4f}")

head=6,629 tail=26,516
nonzero train items=33,145
zero train items=0
val true head share=0.5596
test true head share=0.5370

## 6. Dataset and model

In [7]:
class PairDataset(Dataset):
    def __init__(self, pairs: np.ndarray):
        self.pairs = pairs

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        u, i = self.pairs[idx]
        return int(u), int(i)


class MLP(nn.Module):
    def __init__(self, in_dim: int, hidden: list[int], dropout: float = 0.0):
        super().__init__()

        layers = []
        d = in_dim

        for h in hidden:
            layers.append(nn.Linear(d, h))
            layers.append(nn.ReLU())

            if dropout > 0:
                layers.append(nn.Dropout(dropout))

            d = h

        self.net = nn.Sequential(*layers)
        self.out_dim = d

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class TwoTower(nn.Module):
    """
    Two-Tower baseline:
      user tower: user_id -> MLP
      item tower: item_id + artist_id + album_id -> MLP
    """
    def __init__(
        self,
        num_users: int,
        num_items: int,
        num_artists: int,
        num_albums: int,
        embed_dim: int = 64,
        artist_emb_dim: int = 32,
        album_emb_dim: int = 32,
        hidden: list[int] = [256, 128, 64],
        dropout: float = 0.0,
    ):
        super().__init__()

        self.user_emb = nn.Embedding(num_users, embed_dim)

        self.item_emb = nn.Embedding(num_items, embed_dim)
        self.artist_emb = nn.Embedding(num_artists, artist_emb_dim)
        self.album_emb = nn.Embedding(num_albums, album_emb_dim)

        user_in_dim = embed_dim
        item_in_dim = embed_dim + artist_emb_dim + album_emb_dim

        self.user_mlp = MLP(user_in_dim, hidden, dropout)
        self.item_mlp = MLP(item_in_dim, hidden, dropout)

        self.user_ln = nn.LayerNorm(self.user_mlp.out_dim)
        self.item_ln = nn.LayerNorm(self.item_mlp.out_dim)

        self.init_weights()

    def init_weights(self):
        for emb in [self.user_emb, self.item_emb, self.artist_emb, self.album_emb]:
            nn.init.normal_(emb.weight, std=0.01)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def user_vec(self, u: torch.Tensor) -> torch.Tensor:
        x = self.user_emb(u)
        x = self.user_mlp(x)
        x = self.user_ln(x)
        return x

    def item_vec(self, i: torch.Tensor) -> torch.Tensor:
        item_id_vec = self.item_emb(i)
        artist_vec = self.artist_emb(item_artist_t[i])
        album_vec = self.album_emb(item_album_t[i])

        x = torch.cat([item_id_vec, artist_vec, album_vec], dim=-1)
        x = self.item_mlp(x)
        x = self.item_ln(x)
        return x

    def forward(self, u: torch.Tensor, i: torch.Tensor) -> torch.Tensor:
        uv = F.normalize(self.user_vec(u), dim=-1, eps=1e-6)
        iv = F.normalize(self.item_vec(i), dim=-1, eps=1e-6)
        return (uv * iv).sum(dim=-1)


def inbatch_softmax_loss(user_vecs: torch.Tensor, item_vecs: torch.Tensor):
    u = F.normalize(user_vecs, dim=-1, eps=1e-6)
    v = F.normalize(item_vecs, dim=-1, eps=1e-6)

    logits = u @ v.T
    labels = torch.arange(logits.size(0), device=logits.device)

    return F.cross_entropy(logits, labels)


train_loader = DataLoader(
    PairDataset(train_pairs),
    batch_size=CFG["batch_size"],
    shuffle=True,
    drop_last=True,
    pin_memory=torch.cuda.is_available(),
)

model = TwoTower(
    NUM_USERS,
    NUM_ITEMS,
    NUM_ARTISTS,
    NUM_ALBUMS,
    embed_dim=CFG["embed_dim"],
    artist_emb_dim=CFG["artist_emb_dim"],
    album_emb_dim=CFG["album_emb_dim"],
    hidden=CFG["tower_hidden"],
    dropout=CFG["dropout"],
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=CFG["lr"],
    weight_decay=CFG["weight_decay"],
)

print(model)

TwoTower(
  (user_emb): Embedding(7102, 64)
  (item_emb): Embedding(33145, 64)
  (artist_emb): Embedding(9321, 32)
  (album_emb): Embedding(23839, 32)
  (user_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=64, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (item_mlp): MLP(
    (net): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): ReLU()
      (2): Linear(in_features=256, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=64, bias=True)
      (5): ReLU()
    )
  )
  (user_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
  (item_ln): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
)

## 7. Evaluation

In [8]:
@torch.no_grad()
def evaluate_full_corpus(
    model: nn.Module,
    users: np.ndarray,
    true_items: np.ndarray,
    known_user_items: List[set],
    head_mask: np.ndarray,
    ks: List[int],
    item_freq: np.ndarray,
    user_batch_size: int = 128,
    item_batch_size: int = 8192,
):
    model.eval()

    ranks_all = []
    ranks_head = []
    ranks_tail = []

    max_k = max(ks)

    # Для coverage / popularity / personalization
    recommended_by_k = {k: [] for k in ks}

    # ============================================================
    # 1. Считаем вектора всех items один раз
    # ============================================================

    item_vectors = []

    for s in tqdm(
        range(0, NUM_ITEMS, item_batch_size),
        desc="item vectors",
        leave=False,
    ):
        e = min(s + item_batch_size, NUM_ITEMS)
        idx = torch.arange(s, e, device=device)

        v = model.item_vec(idx)
        v = F.normalize(v, dim=-1, eps=1e-6)

        if not torch.isfinite(v).all():
            raise RuntimeError(f"Non-finite item vectors on item batch {s}:{e}")

        item_vectors.append(v.cpu())

    item_vectors = torch.cat(item_vectors, dim=0).to(device)

    if not torch.isfinite(item_vectors).all():
        raise RuntimeError("Non-finite item vectors after concat")

    # ============================================================
    # 2. Идём по пользователям батчами
    # ============================================================

    for start in tqdm(
        range(0, len(users), user_batch_size),
        desc="eval users",
        leave=False,
    ):
        end = min(start + user_batch_size, len(users))

        bu = users[start:end]
        bi = true_items[start:end]

        ut = torch.tensor(bu, device=device, dtype=torch.long)

        uvec = model.user_vec(ut)
        uvec = F.normalize(uvec, dim=-1, eps=1e-6)

        if not torch.isfinite(uvec).all():
            raise RuntimeError(f"Non-finite user vectors on user batch {start}:{end}")

        scores = (uvec @ item_vectors.T).cpu().numpy()

        if not np.isfinite(scores).all():
            bad = np.sum(~np.isfinite(scores))
            raise RuntimeError(
                f"Non-finite scores in user batch {start}:{end}: {bad} bad values"
            )

        # ========================================================
        # 3. Для каждого пользователя считаем rank и top-K
        # ========================================================

        for row, (u, true_i) in enumerate(zip(bu, bi)):
            u = int(u)
            true_i = int(true_i)

            srow = scores[row].copy()

            if true_i < 0 or true_i >= NUM_ITEMS:
                raise RuntimeError(
                    f"true_i out of bounds: user={u}, true_i={true_i}, NUM_ITEMS={NUM_ITEMS}"
                )

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"Non-finite true item score: user={u}, item={true_i}"
                )

            # Маскируем уже известные items пользователя
            for it in known_user_items[u]:
                if it != true_i:
                    srow[it] = -1e9

            if not np.isfinite(srow[true_i]):
                raise RuntimeError(
                    f"True item was masked or became non-finite: user={u}, item={true_i}"
                )

            # ----------------------------------------------------
            # Rank true item
            # pessimistic tie handling:
            # если у многих items одинаковый score, true item НЕ считается первым
            # ----------------------------------------------------

            true_score = srow[true_i]
            eps = 1e-12

            num_greater = int((srow > true_score + eps).sum())
            num_tied = int((np.abs(srow - true_score) <= eps).sum())

            rank = num_greater + num_tied - 1

            ranks_all.append(rank)

            if head_mask[true_i]:
                ranks_head.append(rank)
            else:
                ranks_tail.append(rank)

            # ----------------------------------------------------
            # Top-K recommendations для coverage/popularity
            # ----------------------------------------------------

            if max_k < len(srow):
                top_unsorted = np.argpartition(-srow, max_k - 1)[:max_k]
                top_idx = top_unsorted[np.argsort(-srow[top_unsorted])]
            else:
                top_idx = np.argsort(-srow)

            for k in ks:
                recommended_by_k[k].append(top_idx[:k].astype(np.int64))

    # ============================================================
    # 4. Accuracy metrics: HR / NDCG
    # ============================================================

    def agg_accuracy(ranks: List[int]) -> Dict[str, float]:
        a = np.asarray(ranks, dtype=np.int64)
        out = {}

        for k in ks:
            if len(a) == 0:
                out[f"HR@{k}"] = np.nan
                out[f"NDCG@{k}"] = np.nan
            else:
                hits = a < k

                out[f"HR@{k}"] = 100.0 * hits.mean()

                out[f"NDCG@{k}"] = 100.0 * np.where(
                    hits,
                    1.0 / np.log2(a + 2),
                    0.0,
                ).mean()

        return out

    # ============================================================
    # 5. Long-tail / coverage metrics
    # ============================================================

    tail_mask = ~head_mask
    num_tail_items = int(tail_mask.sum())

    # item_freq нужен именно здесь
    popularity = np.log1p(item_freq.astype(np.float64))

    long_tail_metrics = {}

    for k in ks:
        recs = np.vstack(recommended_by_k[k])  # shape: (num_eval_users, k)

        unique_recs = np.unique(recs)

        # CatalogCoverage@K
        catalog_coverage = len(unique_recs) / NUM_ITEMS

        # TailCoverage@K
        if num_tail_items > 0:
            tail_coverage = np.sum(tail_mask[unique_recs]) / num_tail_items
        else:
            tail_coverage = np.nan

        # AvgPopularity@K
        avg_popularity = popularity[recs].mean()

        # TailRatio@K
        tail_ratio = tail_mask[recs].mean()

        # Personalization@K
        # 1 - average pairwise overlap / K
        # считаем эффективно через exposure counts
        n_users_eval = recs.shape[0]

        if n_users_eval <= 1:
            personalization = np.nan
        else:
            exposure_counts = np.bincount(
                recs.reshape(-1),
                minlength=NUM_ITEMS,
            )

            pairwise_intersections = np.sum(
                exposure_counts * (exposure_counts - 1) / 2
            )

            num_user_pairs = n_users_eval * (n_users_eval - 1) / 2
            avg_overlap = pairwise_intersections / num_user_pairs

            personalization = 1.0 - avg_overlap / k

        long_tail_metrics[f"CatalogCoverage@{k}"] = 100.0 * catalog_coverage
        long_tail_metrics[f"TailCoverage@{k}"] = 100.0 * tail_coverage
        long_tail_metrics[f"AvgPopularity@{k}"] = float(avg_popularity)
        long_tail_metrics[f"TailRatio@{k}"] = 100.0 * tail_ratio
        long_tail_metrics[f"Personalization@{k}"] = 100.0 * personalization

    return {
        "overall": agg_accuracy(ranks_all),
        "head": agg_accuracy(ranks_head),
        "tail": agg_accuracy(ranks_tail),
        "long_tail": long_tail_metrics,
        "counts": {
            "overall": len(ranks_all),
            "head": len(ranks_head),
            "tail": len(ranks_tail),
        },
    }


def print_metrics(metrics: Dict):
    print("counts:", metrics.get("counts", {}))

    for split in ["overall", "head", "tail"]:
        print(f"[{split}]", metrics[split])

    if "long_tail" in metrics:
        print("[long_tail]", metrics["long_tail"])

In [9]:
def make_head_mask(item_freq: np.ndarray, head_fraction: float) -> np.ndarray:
    num_items = len(item_freq)
    n_head = max(1, int(num_items * head_fraction))

    order = np.argsort(-item_freq)

    current_head_mask = np.zeros(num_items, dtype=bool)
    current_head_mask[order[:n_head]] = True

    return current_head_mask


@torch.no_grad()
def evaluate_head_tail_sweep(
    model: nn.Module,
    method_name: str,
    seed: int,
    head_fractions: List[float],
    test_u: np.ndarray,
    test_i: np.ndarray,
    known_test: List[set],
    item_freq: np.ndarray,
    ks: List[int],
):
    rows = []

    model.eval()

    for hf in head_fractions:
        print("\n" + "=" * 80)
        print(f"{method_name} | seed={seed} | head_fraction={hf} ({100 * hf:.3f}%)")
        print("=" * 80)

        current_head_mask = make_head_mask(
            item_freq=item_freq,
            head_fraction=hf,
        )

        num_head_items = int(current_head_mask.sum())
        num_tail_items = int((~current_head_mask).sum())

        test_head_share = float(current_head_mask[test_i].mean())
        test_tail_share = float((~current_head_mask[test_i]).mean())

        print(f"num_head_items: {num_head_items:,}")
        print(f"num_tail_items: {num_tail_items:,}")
        print(f"test_head_share: {test_head_share:.4f}")
        print(f"test_tail_share: {test_tail_share:.4f}")

        metrics = evaluate_full_corpus(
            model=model,
            users=test_u,
            true_items=test_i,
            known_user_items=known_test,
            head_mask=current_head_mask,
            ks=ks,
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        print_metrics(metrics)

        row = {
            "method": method_name,
            "seed": seed,
            "head_fraction": hf,
            "head_percent": 100.0 * hf,
            "num_head_items": num_head_items,
            "num_tail_items": num_tail_items,
            "test_head_share": test_head_share,
            "test_tail_share": test_tail_share,
        }

        for split in ("overall", "head", "tail"):
            for key, value in metrics[split].items():
                row[f"{split}_{key}"] = value

        if "long_tail" in metrics:
            for key, value in metrics["long_tail"].items():
                row[key] = value

        if "counts" in metrics:
            for key, value in metrics["counts"].items():
                row[f"count_{key}"] = value

        rows.append(row)

    return rows

## 8. Grid search

In [10]:
LR_GRID = [0.001]
DROPOUT_GRID = [0.1]
WD_GRID = [0.0]

combos = list(itertools.product(LR_GRID, DROPOUT_GRID, WD_GRID))
k_main = CFG["eval_k"][-1]  # HR@50

cache_path = Path(CFG["cache_path"])
leaderboard_csv_path = cache_path.with_suffix(".leaderboard.csv")

if CFG["skip_tune_if_cached"] and cache_path.exists():
    best_hp = json.loads(cache_path.read_text())
    print(f"Loaded cached hparams: {best_hp}")

    if leaderboard_csv_path.exists():
        leaderboard_df = pd.read_csv(leaderboard_csv_path)
        print(f"Loaded leaderboard: {leaderboard_csv_path}")
    else:
        leaderboard_df = None
        print("Leaderboard CSV not found.")

else:
    frac = float(CFG.get("tune_val_fraction", 1.0))

    if frac < 1.0 and CFG["tune_fast"]:
        n_tune = max(1, int(len(val_u) * frac))
        _idx = np.random.default_rng(42).choice(len(val_u), n_tune, replace=False)
        val_u_t, val_i_t = val_u[_idx], val_i[_idx]
    else:
        val_u_t, val_i_t = val_u, val_i

    tune_ep = CFG["tune_epochs"] if CFG["tune_fast"] else CFG["final_epochs"]

    print(
        f"Tuning {len(combos)} trials × {tune_ep} ep "
        f"(val subset: {len(val_u_t):,}/{len(val_u):,})"
    )

    best_hr = -1.0
    best_hp = None
    leaderboard = []

    for ti, (lr, dr, wd) in enumerate(combos, 1):
        set_seed(CFG["seed"])

        m = TwoTower(
            NUM_USERS,
            NUM_ITEMS,
            NUM_ARTISTS,
            NUM_ALBUMS,
            embed_dim=CFG["embed_dim"],
            artist_emb_dim=CFG["artist_emb_dim"],
            album_emb_dim=CFG["album_emb_dim"],
            hidden=CFG["tower_hidden"],
            dropout=dr,
        ).to(device)

        opt = torch.optim.Adam(
            m.parameters(),
            lr=lr,
            weight_decay=wd,
        )

        status = "ok"
        error_message = ""
        avg_loss = np.nan
        met = None
        hr = -1.0

        try:
            for ep in range(1, tune_ep + 1):
                m.train()
                total_loss = 0.0
                total_n = 0

                pbar = tqdm(
                    train_loader,
                    desc=f"trial{ti} {ep}/{tune_ep}",
                    leave=False,
                )

                for users_batch, items_batch in pbar:
                    users_batch = users_batch.to(device, non_blocking=True)
                    items_batch = items_batch.to(device, non_blocking=True)

                    user_vecs = m.user_vec(users_batch)
                    item_vecs = m.item_vec(items_batch)

                    loss = inbatch_softmax_loss(user_vecs, item_vecs)

                    if not torch.isfinite(loss):
                        raise RuntimeError(f"Non-finite loss: {loss.item()}")

                    opt.zero_grad(set_to_none=True)
                    loss.backward()

                    torch.nn.utils.clip_grad_norm_(
                        m.parameters(),
                        CFG["grad_clip"],
                    )

                    opt.step()

                    bs = users_batch.size(0)
                    total_loss += loss.item() * bs
                    total_n += bs

                    pbar.set_postfix(loss=f"{loss.item():.4f}")

                avg_loss = total_loss / max(total_n, 1)
                print(f"  trial{ti} ep{ep} loss={avg_loss:.4f}")

            met = evaluate_full_corpus(
                model=m,
                users=val_u_t,
                true_items=val_i_t,
                known_user_items=known_val,
                head_mask=head_mask,
                ks=CFG["eval_k"],
                item_freq=item_freq,
                user_batch_size=CFG["eval_batch_users"],
                item_batch_size=CFG["eval_item_batch"],
            )

            hr = met["overall"][f"HR@{k_main}"]

            if not np.isfinite(hr):
                raise RuntimeError(f"Non-finite HR: {hr}")

        except RuntimeError as e:
            status = "failed"
            error_message = str(e)
            print(f"  trial {ti} FAILED: {e}")

        row = {
            "trial": ti,
            "status": status,
            "error": error_message,
            "lr": lr,
            "dropout": dr,
            "weight_decay": wd,
            "tune_epochs": tune_ep,
            "val_subset_size": len(val_u_t),
            "val_full_size": len(val_u),
            "final_train_loss": avg_loss,
            f"val_HR@{k_main}": hr,
        }

        if met is not None:
            for split in ("overall", "head", "tail"):
                for key, value in met[split].items():
                    row[f"val_{split}_{key}"] = value

            if "long_tail" in met:
                for key, value in met["long_tail"].items():
                    row[f"val_{key}"] = value

            if "counts" in met:
                for key, value in met["counts"].items():
                    row[f"val_count_{key}"] = value

        leaderboard.append(row)

        print(
            f"  trial {ti:3d}/{len(combos)}  "
            f"lr={lr:.0e} dr={dr} wd={wd:.0e}  "
            f"-> val HR@{k_main}={hr:.2f}%"
        )

        if status == "ok" and hr > best_hr:
            best_hr = hr
            best_hp = {
                "lr": lr,
                "dropout": dr,
                "weight_decay": wd,
                f"val_HR@{k_main}": hr,
            }

        del m
        del opt
        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    leaderboard_df = pd.DataFrame(leaderboard).sort_values(
        f"val_HR@{k_main}",
        ascending=False,
        na_position="last",
    )

    leaderboard_df.to_csv(leaderboard_csv_path, index=False)

    if best_hp is None:
        raise RuntimeError("No successful grid-search trial. Check leaderboard for errors.")

    cache_path.write_text(json.dumps(best_hp, indent=2))

    print(f"\nBest val HR@{k_main}={best_hr:.2f}%  ->  {best_hp}")
    print(f"Saved best hparams: {cache_path}")
    print(f"Saved leaderboard CSV: {leaderboard_csv_path}")

leaderboard_df.head(10) if leaderboard_df is not None else None

Tuning 80 trials × 3 ep (val subset: 7,102/7,102)

  trial1 ep1 loss=8.3178

  trial1 ep2 loss=8.2863

  trial1 ep3 loss=8.1143

  trial   1/80  lr=1e-01 dr=0.1 wd=0e+00  -> val HR@50=0.27%

  trial2 ep1 loss=8.3186

  trial2 ep2 loss=8.3187

  trial2 ep3 loss=8.3190

  trial   2/80  lr=1e-01 dr=0.1 wd=1e-01  -> val HR@50=0.00%

  trial3 ep1 loss=8.3181

  trial3 ep2 loss=8.3182

  trial3 ep3 loss=8.3182

  trial   3/80  lr=1e-01 dr=0.1 wd=1e-02  -> val HR@50=0.00%

  trial4 ep1 loss=8.3180

  trial4 ep2 loss=8.3179

  trial4 ep3 loss=8.3179

  trial   4/80  lr=1e-01 dr=0.1 wd=1e-03  -> val HR@50=0.00%

  trial5 ep1 loss=8.3179

  trial5 ep2 loss=8.3178

  trial5 ep3 loss=8.3178

  trial   5/80  lr=1e-01 dr=0.3 wd=0e+00  -> val HR@50=0.10%

  trial6 ep1 loss=8.3199

  trial6 ep2 loss=8.3201

  trial6 ep3 loss=8.3208

  trial   6/80  lr=1e-01 dr=0.3 wd=1e-01  -> val HR@50=0.00%

  trial7 ep1 loss=8.3183

  trial7 ep2 loss=8.3185

  trial7 ep3 loss=8.3184

  trial   7/80  lr=1e-01 dr=0.3 wd=1e-02  -> val HR@50=0.00%

  trial8 ep1 loss=8.3182

  trial8 ep2 loss=8.3179

  trial8 ep3 loss=8.3180

  trial   8/80  lr=1e-01 dr=0.3 wd=1e-03  -> val HR@50=0.00%

  trial9 ep1 loss=8.3179

  trial9 ep2 loss=8.3178

  trial9 ep3 loss=8.3178

  trial   9/80  lr=1e-01 dr=0.5 wd=0e+00  -> val HR@50=0.13%

  trial10 ep1 loss=8.3193

  trial10 ep2 loss=8.3204

  trial10 ep3 loss=8.3210

  trial  10/80  lr=1e-01 dr=0.5 wd=1e-01  -> val HR@50=0.00%

  trial11 ep1 loss=8.3186

  trial11 ep2 loss=8.3184

  trial11 ep3 loss=8.3185

  trial  11/80  lr=1e-01 dr=0.5 wd=1e-02  -> val HR@50=0.00%

  trial12 ep1 loss=8.3184

  trial12 ep2 loss=8.3181

  trial12 ep3 loss=8.3182

  trial  12/80  lr=1e-01 dr=0.5 wd=1e-03  -> val HR@50=0.00%

  trial13 ep1 loss=8.3180

  trial13 ep2 loss=8.3178

  trial13 ep3 loss=8.3178

  trial  13/80  lr=1e-01 dr=0.7 wd=0e+00  -> val HR@50=0.13%

  trial14 ep1 loss=8.3201

  trial14 ep2 loss=8.3201

  trial14 ep3 loss=8.3205

  trial  14/80  lr=1e-01 dr=0.7 wd=1e-01  -> val HR@50=0.00%

  trial15 ep1 loss=8.3189

  trial15 ep2 loss=8.3186

  trial15 ep3 loss=8.3186

  trial  15/80  lr=1e-01 dr=0.7 wd=1e-02  -> val HR@50=0.00%

  trial16 ep1 loss=8.3187

  trial16 ep2 loss=8.3182

  trial16 ep3 loss=8.3182

  trial  16/80  lr=1e-01 dr=0.7 wd=1e-03  -> val HR@50=0.00%

  trial17 ep1 loss=8.3187

  trial17 ep2 loss=8.3180

  trial17 ep3 loss=8.3179

  trial  17/80  lr=1e-01 dr=0.9 wd=0e+00  -> val HR@50=0.18%

  trial18 ep1 loss=8.3206

  trial18 ep2 loss=8.3196

  trial18 ep3 loss=8.3201

  trial  18/80  lr=1e-01 dr=0.9 wd=1e-01  -> val HR@50=0.00%

  trial19 ep1 loss=8.3195

  trial19 ep2 loss=8.3193

  trial19 ep3 loss=8.3193

  trial  19/80  lr=1e-01 dr=0.9 wd=1e-02  -> val HR@50=0.00%

  trial20 ep1 loss=8.3184

  trial20 ep2 loss=8.3196

  trial20 ep3 loss=8.3191

  trial  20/80  lr=1e-01 dr=0.9 wd=1e-03  -> val HR@50=0.00%

  trial21 ep1 loss=8.3178

  trial21 ep2 loss=8.2110

  trial21 ep3 loss=8.0698

  trial  21/80  lr=1e-02 dr=0.1 wd=0e+00  -> val HR@50=0.32%

  trial22 ep1 loss=8.3179

  trial22 ep2 loss=8.3178

  trial22 ep3 loss=8.3178

  trial  22/80  lr=1e-02 dr=0.1 wd=1e-01  -> val HR@50=0.00%

  trial23 ep1 loss=8.3179

  trial23 ep2 loss=8.3178

  trial23 ep3 loss=8.3178

  trial  23/80  lr=1e-02 dr=0.1 wd=1e-02  -> val HR@50=0.00%

  trial24 ep1 loss=8.3179

  trial24 ep2 loss=8.3178

  trial24 ep3 loss=8.3178

  trial  24/80  lr=1e-02 dr=0.1 wd=1e-03  -> val HR@50=0.00%

  trial25 ep1 loss=8.3179

  trial25 ep2 loss=8.3178

  trial25 ep3 loss=8.3178

  trial  25/80  lr=1e-02 dr=0.3 wd=0e+00  -> val HR@50=0.06%

  trial26 ep1 loss=8.3181

  trial26 ep2 loss=8.3179

  trial26 ep3 loss=8.3179

  trial  26/80  lr=1e-02 dr=0.3 wd=1e-01  -> val HR@50=0.00%

  trial27 ep1 loss=8.3180

  trial27 ep2 loss=8.3178

  trial27 ep3 loss=8.3179

  trial  27/80  lr=1e-02 dr=0.3 wd=1e-02  -> val HR@50=0.00%

  trial28 ep1 loss=8.3179

  trial28 ep2 loss=8.3178

  trial28 ep3 loss=8.3178

  trial  28/80  lr=1e-02 dr=0.3 wd=1e-03  -> val HR@50=0.00%

  trial29 ep1 loss=8.3180

  trial29 ep2 loss=8.3178

  trial29 ep3 loss=8.3178

  trial  29/80  lr=1e-02 dr=0.5 wd=0e+00  -> val HR@50=0.14%

  trial30 ep1 loss=8.3182

  trial30 ep2 loss=8.3180

  trial30 ep3 loss=8.3179

  trial  30/80  lr=1e-02 dr=0.5 wd=1e-01  -> val HR@50=0.00%

  trial31 ep1 loss=8.3181

  trial31 ep2 loss=8.3179

  trial31 ep3 loss=8.3179

  trial  31/80  lr=1e-02 dr=0.5 wd=1e-02  -> val HR@50=0.00%

  trial32 ep1 loss=8.3180

  trial32 ep2 loss=8.3178

  trial32 ep3 loss=8.3178

  trial  32/80  lr=1e-02 dr=0.5 wd=1e-03  -> val HR@50=0.00%

  trial33 ep1 loss=8.3181

  trial33 ep2 loss=8.3178

  trial33 ep3 loss=8.3178

  trial  33/80  lr=1e-02 dr=0.7 wd=0e+00  -> val HR@50=0.10%

  trial34 ep1 loss=8.3184

  trial34 ep2 loss=8.3180

  trial34 ep3 loss=8.3179

  trial  34/80  lr=1e-02 dr=0.7 wd=1e-01  -> val HR@50=0.00%

  trial35 ep1 loss=8.3182

  trial35 ep2 loss=8.3179

  trial35 ep3 loss=8.3179

  trial  35/80  lr=1e-02 dr=0.7 wd=1e-02  -> val HR@50=0.00%

  trial36 ep1 loss=8.3181

  trial36 ep2 loss=8.3179

  trial36 ep3 loss=8.3178

  trial  36/80  lr=1e-02 dr=0.7 wd=1e-03  -> val HR@50=0.00%

  trial37 ep1 loss=8.3209

  trial37 ep2 loss=8.3185

  trial37 ep3 loss=8.3181

  trial  37/80  lr=1e-02 dr=0.9 wd=0e+00  -> val HR@50=0.21%

  trial38 ep1 loss=8.3206

  trial38 ep2 loss=8.3184

  trial38 ep3 loss=8.3180

  trial  38/80  lr=1e-02 dr=0.9 wd=1e-01  -> val HR@50=0.00%

  trial39 ep1 loss=8.3193

  trial39 ep2 loss=8.3179

  trial39 ep3 loss=8.3179

  trial  39/80  lr=1e-02 dr=0.9 wd=1e-02  -> val HR@50=0.00%

  trial40 ep1 loss=8.3200

  trial40 ep2 loss=8.3179

  trial40 ep3 loss=8.3179

  trial  40/80  lr=1e-02 dr=0.9 wd=1e-03  -> val HR@50=0.00%

  trial41 ep1 loss=8.3177

  trial41 ep2 loss=8.1639

  trial41 ep3 loss=8.0553

  trial  41/80  lr=1e-03 dr=0.1 wd=0e+00  -> val HR@50=0.48%

  trial42 ep1 loss=8.3179

  trial42 ep2 loss=8.3178

  trial42 ep3 loss=8.3178

  trial  42/80  lr=1e-03 dr=0.1 wd=1e-01  -> val HR@50=0.00%

  trial43 ep1 loss=8.3179

  trial43 ep2 loss=8.3178

  trial43 ep3 loss=8.3178

  trial  43/80  lr=1e-03 dr=0.1 wd=1e-02  -> val HR@50=0.00%

  trial44 ep1 loss=8.3179

  trial44 ep2 loss=8.3178

  trial44 ep3 loss=8.3178

  trial  44/80  lr=1e-03 dr=0.1 wd=1e-03  -> val HR@50=0.00%

  trial45 ep1 loss=8.3181

  trial45 ep2 loss=8.3178

  trial45 ep3 loss=8.3173

  trial  45/80  lr=1e-03 dr=0.3 wd=0e+00  -> val HR@50=0.10%

  trial46 ep1 loss=8.3181

  trial46 ep2 loss=8.3178

  trial46 ep3 loss=8.3178

  trial  46/80  lr=1e-03 dr=0.3 wd=1e-01  -> val HR@50=0.00%

  trial47 ep1 loss=8.3181

  trial47 ep2 loss=8.3178

  trial47 ep3 loss=8.3178

  trial  47/80  lr=1e-03 dr=0.3 wd=1e-02  -> val HR@50=0.00%

  trial48 ep1 loss=8.3181

  trial48 ep2 loss=8.3178

  trial48 ep3 loss=8.3178

  trial  48/80  lr=1e-03 dr=0.3 wd=1e-03  -> val HR@50=0.00%

  trial49 ep1 loss=8.3184

  trial49 ep2 loss=8.3178

  trial49 ep3 loss=8.3178

  trial  49/80  lr=1e-03 dr=0.5 wd=0e+00  -> val HR@50=0.17%

  trial50 ep1 loss=8.3183

  trial50 ep2 loss=8.3179

  trial50 ep3 loss=8.3179

  trial  50/80  lr=1e-03 dr=0.5 wd=1e-01  -> val HR@50=0.00%

  trial51 ep1 loss=8.3183

  trial51 ep2 loss=8.3178

  trial51 ep3 loss=8.3178

  trial  51/80  lr=1e-03 dr=0.5 wd=1e-02  -> val HR@50=0.00%

  trial52 ep1 loss=8.3183

  trial52 ep2 loss=8.3178

  trial52 ep3 loss=8.3178

  trial  52/80  lr=1e-03 dr=0.5 wd=1e-03  -> val HR@50=0.00%

  trial53 ep1 loss=8.3192

  trial53 ep2 loss=8.3180

  trial53 ep3 loss=8.3179

  trial  53/80  lr=1e-03 dr=0.7 wd=0e+00  -> val HR@50=0.08%

  trial54 ep1 loss=8.3185

  trial54 ep2 loss=8.3179

  trial54 ep3 loss=8.3180

  trial  54/80  lr=1e-03 dr=0.7 wd=1e-01  -> val HR@50=0.00%

  trial55 ep1 loss=8.3186

  trial55 ep2 loss=8.3179

  trial55 ep3 loss=8.3179

  trial  55/80  lr=1e-03 dr=0.7 wd=1e-02  -> val HR@50=0.00%

  trial56 ep1 loss=8.3188

  trial56 ep2 loss=8.3179

  trial56 ep3 loss=8.3178

  trial  56/80  lr=1e-03 dr=0.7 wd=1e-03  -> val HR@50=0.00%

  trial57 ep1 loss=8.3265

  trial57 ep2 loss=8.3245

  trial57 ep3 loss=8.3225

  trial  57/80  lr=1e-03 dr=0.9 wd=0e+00  -> val HR@50=0.07%

  trial58 ep1 loss=8.3221

  trial58 ep2 loss=8.3181

  trial58 ep3 loss=8.3180

  trial  58/80  lr=1e-03 dr=0.9 wd=1e-01  -> val HR@50=0.00%

  trial59 ep1 loss=8.3222

  trial59 ep2 loss=8.3180

  trial59 ep3 loss=8.3179

  trial  59/80  lr=1e-03 dr=0.9 wd=1e-02  -> val HR@50=0.00%

  trial60 ep1 loss=8.3241

  trial60 ep2 loss=8.3187

  trial60 ep3 loss=8.3179

  trial  60/80  lr=1e-03 dr=0.9 wd=1e-03  -> val HR@50=0.54%

  trial61 ep1 loss=8.3186

  trial61 ep2 loss=8.3165

  trial61 ep3 loss=8.2782

  trial  61/80  lr=1e-04 dr=0.1 wd=0e+00  -> val HR@50=0.23%

  trial62 ep1 loss=8.3185

  trial62 ep2 loss=8.3178

  trial62 ep3 loss=8.3178

  trial  62/80  lr=1e-04 dr=0.1 wd=1e-01  -> val HR@50=0.18%

  trial63 ep1 loss=8.3185

  trial63 ep2 loss=8.3178

  trial63 ep3 loss=8.3165

  trial  63/80  lr=1e-04 dr=0.1 wd=1e-02  -> val HR@50=0.54%

  trial64 ep1 loss=8.3185

  trial64 ep2 loss=8.3164

  trial64 ep3 loss=8.2334

  trial  64/80  lr=1e-04 dr=0.1 wd=1e-03  -> val HR@50=0.39%

  trial65 ep1 loss=8.3194

  trial65 ep2 loss=8.3180

  trial65 ep3 loss=8.3179

  trial  65/80  lr=1e-04 dr=0.3 wd=0e+00  -> val HR@50=0.21%

  trial66 ep1 loss=8.3192

  trial66 ep2 loss=8.3178

  trial66 ep3 loss=8.3178

  trial  66/80  lr=1e-04 dr=0.3 wd=1e-01  -> val HR@50=0.20%

  trial67 ep1 loss=8.3193

  trial67 ep2 loss=8.3179

  trial67 ep3 loss=8.3178

  trial  67/80  lr=1e-04 dr=0.3 wd=1e-02  -> val HR@50=0.15%

  trial68 ep1 loss=8.3194

  trial68 ep2 loss=8.3179

  trial68 ep3 loss=8.3178

  trial  68/80  lr=1e-04 dr=0.3 wd=1e-03  -> val HR@50=0.20%

  trial69 ep1 loss=8.3209

  trial69 ep2 loss=8.3184

  trial69 ep3 loss=8.3181

  trial  69/80  lr=1e-04 dr=0.5 wd=0e+00  -> val HR@50=0.13%

  trial70 ep1 loss=8.3200

  trial70 ep2 loss=8.3179

  trial70 ep3 loss=8.3178

  trial  70/80  lr=1e-04 dr=0.5 wd=1e-01  -> val HR@50=0.23%

  trial71 ep1 loss=8.3204

  trial71 ep2 loss=8.3179

  trial71 ep3 loss=8.3179

  trial  71/80  lr=1e-04 dr=0.5 wd=1e-02  -> val HR@50=0.28%

  trial72 ep1 loss=8.3207

  trial72 ep2 loss=8.3182

  trial72 ep3 loss=8.3179

  trial  72/80  lr=1e-04 dr=0.5 wd=1e-03  -> val HR@50=0.32%

  trial73 ep1 loss=8.3239

  trial73 ep2 loss=8.3199

  trial73 ep3 loss=8.3187

  trial  73/80  lr=1e-04 dr=0.7 wd=0e+00  -> val HR@50=0.08%

  trial74 ep1 loss=8.3219

  trial74 ep2 loss=8.3179

  trial74 ep3 loss=8.3179

  trial  74/80  lr=1e-04 dr=0.7 wd=1e-01  -> val HR@50=0.13%

  trial75 ep1 loss=8.3227

  trial75 ep2 loss=8.3181

  trial75 ep3 loss=8.3179

  trial  75/80  lr=1e-04 dr=0.7 wd=1e-02  -> val HR@50=0.32%

  trial76 ep1 loss=8.3235

  trial76 ep2 loss=8.3191

  trial76 ep3 loss=8.3181

  trial  76/80  lr=1e-04 dr=0.7 wd=1e-03  -> val HR@50=0.27%

  trial77 ep1 loss=8.3272

  trial77 ep2 loss=8.3268

  trial77 ep3 loss=8.3263

  trial  77/80  lr=1e-04 dr=0.9 wd=0e+00  -> val HR@50=0.07%

  trial78 ep1 loss=8.3270

  trial78 ep2 loss=8.3250

  trial78 ep3 loss=8.3209

  trial  78/80  lr=1e-04 dr=0.9 wd=1e-01  -> val HR@50=0.25%

  trial79 ep1 loss=8.3273

  trial79 ep2 loss=8.3262

  trial79 ep3 loss=8.3225

  trial  79/80  lr=1e-04 dr=0.9 wd=1e-02  -> val HR@50=0.49%

  trial80 ep1 loss=8.3272

  trial80 ep2 loss=8.3266

  trial80 ep3 loss=8.3256

  trial  80/80  lr=1e-04 dr=0.9 wd=1e-03  -> val HR@50=0.39%

Best val HR@50=0.54%  ->  {'lr': 0.001, 'dropout': 0.9, 'weight_decay': 0.001, 'val_HR@50': 0.5350605463249789}
Saved best hparams: best_hparams_yambda_likes_features.json
Saved leaderboard CSV: best_hparams_yambda_likes_features.leaderboard.csv

,trial,status,error,lr,dropout,weight_decay,tune_epochs,val_subset_size,val_full_size,final_train_loss,...,val_TailRatio@10,val_Personalization@10,val_CatalogCoverage@50,val_TailCoverage@50,val_AvgPopularity@50,val_TailRatio@50,val_Personalization@50,val_count_overall,val_count_head,val_count_tail
62,63,ok,,0.0001,0.1,0.010,3,7102,7102,8.316529,...,44.645170,83.326396,3.780359,3.205612,2.991524,61.610532,81.245740,7102,3974,3128
59,60,ok,,0.0010,0.9,0.001,3,7102,7102,8.317935,...,50.901155,1.821023,0.229296,0.169709,3.248158,52.811321,1.672336,7102,3974,3128
78,79,ok,,0.0001,0.9,0.010,3,7102,7102,8.322457,...,40.143622,2.314196,0.208176,0.139538,3.427526,48.813855,1.849968,7102,3974,3128
40,41,ok,,0.0010,0.1,0.000,3,7102,7102,8.055319,...,78.687694,99.817189,79.526324,79.054156,2.593676,77.902844,99.614877,7102,3974,3128
63,64,ok,,0.0001,0.1,0.001,3,7102,7102,8.233377,...,80.361870,99.669102,83.542012,83.225223,2.556545,80.294002,99.301153,7102,3974,3128
79,80,ok,,0.0001,0.9,0.001,3,7102,7102,8.325608,...,32.899183,44.088285,2.066677,1.674461,3.058578,50.826809,38.365570,7102,3974,3128
74,75,ok,,0.0001,0.7,0.010,3,7102,7102,8.317879,...,60.004224,1.272647,0.211193,0.158395,3.146612,56.170375,1.327517,7102,3974,3128
20,21,ok,,0.0100,0.1,0.000,3,7102,7102,8.069846,...,85.387215,97.410583,34.119777,34.311359,2.496284,82.497043,98.298972,7102,3974,3128
71,72,ok,,0.0001,0.5,0.001,3,7102,7102,8.317890,...,70.264714,0.722323,0.178006,0.139538,2.998956,62.249507,0.824661,7102,3974,3128
70,71,ok,,0.0001,0.5,0.010,3,7102,7102,8.317851,...,50.418192,1.049374,0.271534,0.214965,3.090882,60.171219,1.020984,7102,3974,3128

## 9. Final training

In [11]:
HEAD_FRACTIONS = [0.001, 0.005, 0.01, 0.05, 0.20]

all_rows = []
all_test = []
all_sweep_rows = []

print("Using best_hp:", best_hp)

for seed in CFG["seeds"]:
    print("\n" + "=" * 80)
    print(f"TwoTower seed {seed}")
    print("=" * 80)

    set_seed(seed)

    model = TwoTower(
        NUM_USERS,
        NUM_ITEMS,
        NUM_ARTISTS,
        NUM_ALBUMS,
        embed_dim=CFG["embed_dim"],
        artist_emb_dim=CFG["artist_emb_dim"],
        album_emb_dim=CFG["album_emb_dim"],
        hidden=CFG["tower_hidden"],
        dropout=best_hp["dropout"],
    ).to(device)

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=best_hp["lr"],
        weight_decay=best_hp["weight_decay"],
    )

    best_val_hr50 = -1.0
    best_state = None

    # -------------------------
    # Train
    # -------------------------
    for epoch in range(1, CFG["final_epochs"] + 1):
        model.train()
        total_loss = 0.0
        total_n = 0

        pbar = tqdm(
            train_loader,
            desc=f"seed {seed} train {epoch}/{CFG['final_epochs']}",
            leave=False,
        )

        for users_batch, items_batch in pbar:
            users_batch = users_batch.to(device, non_blocking=True)
            items_batch = items_batch.to(device, non_blocking=True)

            user_vecs = model.user_vec(users_batch)
            item_vecs = model.item_vec(items_batch)

            loss = inbatch_softmax_loss(user_vecs, item_vecs)

            if not torch.isfinite(loss):
                raise RuntimeError(
                    f"Non-finite loss at seed={seed}, epoch={epoch}: {loss.item()}"
                )

            optimizer.zero_grad(set_to_none=True)
            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                CFG["grad_clip"],
            )

            optimizer.step()

            bs = users_batch.size(0)
            total_loss += loss.item() * bs
            total_n += bs

            pbar.set_postfix(loss=f"{loss.item():.4f}")

        avg_loss = total_loss / max(total_n, 1)
        print(f"seed {seed} epoch {epoch}: train loss = {avg_loss:.4f}")

        # -------------------------
        # Validation
        # -------------------------
        val_metrics = evaluate_full_corpus(
            model=model,
            users=val_u,
            true_items=val_i,
            known_user_items=known_val,
            head_mask=head_mask,
            ks=CFG["eval_k"],
            item_freq=item_freq,
            user_batch_size=CFG["eval_batch_users"],
            item_batch_size=CFG["eval_item_batch"],
        )

        hr50 = val_metrics["overall"].get("HR@50", -1.0)

        if hr50 > best_val_hr50:
            best_val_hr50 = hr50
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in model.state_dict().items()
            }

            print(f"new best val HR@50 = {best_val_hr50:.4f}")

    print(f"seed {seed} best val HR@50: {best_val_hr50:.4f}")

    assert best_state is not None

    model.load_state_dict(best_state)
    model.to(device)
    model.eval()

    # -------------------------
    # Test on default head_mask
    # -------------------------
    test_metrics = evaluate_full_corpus(
        model=model,
        users=test_u,
        true_items=test_i,
        known_user_items=known_test,
        head_mask=head_mask,
        ks=CFG["eval_k"],
        item_freq=item_freq,
        user_batch_size=CFG["eval_batch_users"],
        item_batch_size=CFG["eval_item_batch"],
    )

    print("TEST METRICS")
    print_metrics(test_metrics)

    all_test.append(test_metrics)

    row = {
        "method": "TwoTower",
        "seed": seed,
        "lr": best_hp["lr"],
        "dropout": best_hp["dropout"],
        "weight_decay": best_hp["weight_decay"],
        "best_val_HR@50": best_val_hr50,
    }

    for split in ("overall", "head", "tail"):
        for key, value in test_metrics[split].items():
            row[f"test_{split}_{key}"] = value

    if "long_tail" in test_metrics:
        for key, value in test_metrics["long_tail"].items():
            row[f"test_{key}"] = value

    if "counts" in test_metrics:
        for key, value in test_metrics["counts"].items():
            row[f"test_count_{key}"] = value

    all_rows.append(row)

    # -------------------------
    # Head/tail threshold sweep
    # -------------------------
    sweep_rows_seed = evaluate_head_tail_sweep(
        model=model,
        method_name="TwoTower",
        seed=seed,
        head_fractions=HEAD_FRACTIONS,
        test_u=test_u,
        test_i=test_i,
        known_test=known_test,
        item_freq=item_freq,
        ks=CFG["eval_k"],
    )

    all_sweep_rows.extend(sweep_rows_seed)

    del model
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


metrics_df = pd.DataFrame(all_rows)
sweep_df = pd.DataFrame(all_sweep_rows)

metrics_df

Using best_hp: {'lr': 0.001, 'dropout': 0.9, 'weight_decay': 0.001, 'val_HR@50': 0.5350605463249789}

================================================================================
TwoTower seed 0
================================================================================

seed 0 epoch 1: train loss = 8.3241

new best val HR@50 = 0.9716

seed 0 epoch 2: train loss = 8.3187

seed 0 epoch 3: train loss = 8.3179

seed 0 epoch 4: train loss = 8.3179

seed 0 epoch 5: train loss = 8.3179

seed 0 epoch 6: train loss = 8.3179

seed 0 epoch 7: train loss = 8.3178

seed 0 epoch 8: train loss = 8.3178

seed 0 epoch 9: train loss = 8.3178

seed 0 epoch 10: train loss = 8.3178

seed 0 epoch 11: train loss = 8.3178

seed 0 epoch 12: train loss = 8.3178

seed 0 epoch 13: train loss = 8.3178

seed 0 epoch 14: train loss = 8.3178

seed 0 epoch 15: train loss = 8.3178

seed 0 epoch 16: train loss = 8.3178

seed 0 epoch 17: train loss = 8.3178

seed 0 epoch 18: train loss = 8.3178

seed 0 epoch 19: train loss = 8.3178

seed 0 epoch 20: train loss = 8.3178

seed 0 best val HR@50: 0.9716

TEST METRICS
counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 0.7865757734661771, 'NDCG@10': 0.35421024330288675, 'HR@50': 1.3371788148925015, 'NDCG@50': 0.4829051903349829}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.003771307889576105, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 0.1802309208673613, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.11313923668728315, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 41.972965361869896, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower | seed=0 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0266
test_tail_share: 0.9734

counts: {'overall': 7102, 'head': 189, 'tail': 6913}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 10.582010582010582, 'NDCG@10': 4.51960518980141, 'HR@50': 16.93121693121693, 'NDCG@50': 6.05529578087621}
[tail] {'HR@10': 0.14465499783017502, 'NDCG@10': 0.07185772994137767, 'HR@50': 0.27484449587733256, 'NDCG@50': 0.10087508944771027}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.042280744141096886, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 72.21064488876372, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.18724329548200047, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 90.69698676429175, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower | seed=0 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0646
test_tail_share: 0.9354

counts: {'overall': 7102, 'head': 459, 'tail': 6643}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 5.228758169934641, 'NDCG@10': 2.163889824758923, 'HR@50': 8.061002178649238, 'NDCG@50': 2.8495337810224526}
[tail] {'HR@10': 0.09032063826584374, 'NDCG@10': 0.0538510369400669, 'HR@50': 0.21074815595363539, 'NDCG@50': 0.08036495415449635}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.03335354760460885, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 52.92030413967896, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.17889630078835658, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 84.90960292875246, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower | seed=0 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1035
test_tail_share: 0.8965

counts: {'overall': 7102, 'head': 735, 'tail': 6367}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 3.2653061224489797, 'NDCG@10': 1.3513271150535315, 'HR@50': 5.170068027210884, 'NDCG@50': 1.8034899985417603}
[tail] {'HR@10': 0.09423590387937804, 'NDCG@10': 0.05618539946487583, 'HR@50': 0.20417779173865241, 'NDCG@50': 0.08107982519387952}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.03352227707685744, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 52.92030413967896, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.17675382458706648, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 84.14277668262461, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower | seed=0 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2858
test_tail_share: 0.7142

counts: {'overall': 7102, 'head': 2030, 'tail': 5072}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 1.4285714285714286, 'NDCG@10': 0.6344162032512632, 'HR@50': 2.167487684729064, 'NDCG@50': 0.8093456339081812}
[tail] {'HR@10': 0.01971608832807571, 'NDCG@10': 0.012439466750225898, 'HR@50': 0.13801261829652997, 'NDCG@50': 0.03920125376656486}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.025406504065040653, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 23.40326668544072, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.16196646341463414, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 74.14305829343847, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower | seed=0 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5370
test_tail_share: 0.4630

counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.42241622078287805, 'NDCG@10': 0.190222172339793, 'HR@50': 0.7181075753308926, 'NDCG@50': 0.25933545422946}
[head] {'HR@10': 0.7865757734661771, 'NDCG@10': 0.35421024330288675, 'HR@50': 1.3371788148925015, 'NDCG@50': 0.4829051903349829}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.05430683360989592, 'TailCoverage@10': 0.003771307889576105, 'AvgPopularity@10': 5.012285910801514, 'TailRatio@10': 0.1802309208673613, 'Personalization@10': 6.434834063970829, 'CatalogCoverage@50': 0.20214210288127923, 'TailCoverage@50': 0.11313923668728315, 'AvgPopularity@50': 3.547881524274075, 'TailRatio@50': 41.972965361869896, 'Personalization@50': 2.8568556885562812}

================================================================================
TwoTower seed 1
================================================================================

seed 1 epoch 1: train loss = 8.3239

new best val HR@50 = 0.7181

seed 1 epoch 2: train loss = 8.3186

seed 1 epoch 3: train loss = 8.3180

seed 1 epoch 4: train loss = 8.3179

seed 1 epoch 5: train loss = 8.3179

seed 1 epoch 6: train loss = 8.3178

seed 1 epoch 7: train loss = 8.3179

seed 1 epoch 8: train loss = 8.3178

seed 1 epoch 9: train loss = 8.3178

seed 1 epoch 10: train loss = 8.3178

seed 1 epoch 11: train loss = 8.3178

seed 1 epoch 12: train loss = 8.3178

seed 1 epoch 13: train loss = 8.3178

seed 1 epoch 14: train loss = 8.3178

seed 1 epoch 15: train loss = 8.3178

seed 1 epoch 16: train loss = 8.3178

seed 1 epoch 17: train loss = 8.3178

seed 1 epoch 18: train loss = 8.3178

seed 1 epoch 19: train loss = 8.3178

seed 1 epoch 20: train loss = 8.3178

seed 1 best val HR@50: 0.7181

TEST METRICS
counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 0.4457262716308337, 'NDCG@10': 0.19244615989804395, 'HR@50': 0.9438909281594127, 'NDCG@50': 0.30717891561120847}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.09124087591240876, 'NDCG@50': 0.01871396594318118}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.018856539447880526, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 30.03379329766263, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.13199577613516367, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 44.52407772458463, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower | seed=1 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0266
test_tail_share: 0.9734

counts: {'overall': 7102, 'head': 189, 'tail': 6913}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 5.82010582010582, 'NDCG@10': 2.91005291005291, 'HR@50': 9.523809523809524, 'NDCG@50': 3.8868441082806777}
[tail] {'HR@10': 0.08679299869810501, 'NDCG@10': 0.026615022978611253, 'HR@50': 0.30377549544336757, 'NDCG@50': 0.07211028029759593}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.039260690988161394, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 91.0616727682343, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.19328340178787146, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 96.39594480428049, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower | seed=1 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0646
test_tail_share: 0.9354

counts: {'overall': 7102, 'head': 459, 'tail': 6643}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 2.3965141612200433, 'NDCG@10': 1.1982570806100217, 'HR@50': 4.357298474945534, 'NDCG@50': 1.6891082602920386}
[tail] {'HR@10': 0.09032063826584374, 'NDCG@10': 0.027696771616910972, 'HR@50': 0.2860153545085052, 'NDCG@50': 0.06891633489210947}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.03941782898726501, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 91.0616727682343, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.19102486355366888, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 94.46691072937202, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower | seed=1 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1035
test_tail_share: 0.8965

counts: {'overall': 7102, 'head': 735, 'tail': 6367}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 1.4965986394557822, 'NDCG@10': 0.7482993197278911, 'HR@50': 2.7210884353741496, 'NDCG@50': 1.0548308727538036}
[tail] {'HR@10': 0.09423590387937804, 'NDCG@10': 0.028897385558526712, 'HR@50': 0.2984136956180305, 'NDCG@50': 0.07190375572299093}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.03961723654537697, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 91.0616727682343, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.18894374352410556, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 92.50633624331175, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower | seed=1 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2858
test_tail_share: 0.7142

counts: {'overall': 7102, 'head': 2030, 'tail': 5072}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 0.7881773399014778, 'NDCG@10': 0.34402410598046174, 'HR@50': 1.477832512315271, 'NDCG@50': 0.5131094621533611}
[tail] {'HR@10': 0.01971608832807571, 'NDCG@10': 0.007023012364117157, 'HR@50': 0.1774447949526814, 'NDCG@50': 0.03775624920958316}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.02858231707317073, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 59.94931005350605, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.16831808943089432, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 74.71219374823993, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower | seed=1 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5370
test_tail_share: 0.4630

counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.23936919177696422, 'NDCG@10': 0.10334971189117709, 'HR@50': 0.5491410870177414, 'NDCG@50': 0.17362882345287647}
[head] {'HR@10': 0.4457262716308337, 'NDCG@10': 0.19244615989804395, 'HR@50': 0.9438909281594127, 'NDCG@50': 0.30717891561120847}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.09124087591240876, 'NDCG@50': 0.01871396594318118}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.018856539447880526, 'AvgPopularity@10': 3.8574206006812597, 'TailRatio@10': 30.03379329766263, 'Personalization@10': 3.3042391013422545, 'CatalogCoverage@50': 0.19912505656961835, 'TailCoverage@50': 0.13199577613516367, 'AvgPopularity@50': 3.3547174895350373, 'TailRatio@50': 44.52407772458463, 'Personalization@50': 3.2456213801499656}

================================================================================
TwoTower seed 2
================================================================================

seed 2 epoch 1: train loss = 8.3241

new best val HR@50 = 0.4928

seed 2 epoch 2: train loss = 8.3188

new best val HR@50 = 0.5069

seed 2 epoch 3: train loss = 8.3180

new best val HR@50 = 0.5351

seed 2 epoch 4: train loss = 8.3179

seed 2 epoch 5: train loss = 8.3179

seed 2 epoch 6: train loss = 8.3178

seed 2 epoch 7: train loss = 8.3178

seed 2 epoch 8: train loss = 8.3178

seed 2 epoch 9: train loss = 8.3178

seed 2 epoch 10: train loss = 8.3178

seed 2 epoch 11: train loss = 8.3178

seed 2 epoch 12: train loss = 8.3178

seed 2 epoch 13: train loss = 8.3178

seed 2 epoch 14: train loss = 8.3178

seed 2 epoch 15: train loss = 8.3178

seed 2 epoch 16: train loss = 8.3178

seed 2 epoch 17: train loss = 8.3178

seed 2 epoch 18: train loss = 8.3178

seed 2 epoch 19: train loss = 8.3178

seed 2 epoch 20: train loss = 8.3178

seed 2 best val HR@50: 0.5351

TEST METRICS
counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.9963293130571578, 'NDCG@50': 0.20793023223214177}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.12165450121654502, 'NDCG@50': 0.022930741785925888}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.05279831045406547, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 80.09293156857224, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.13576708402473978, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 44.19262179667699, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower | seed=2 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0266
test_tail_share: 0.9734

counts: {'overall': 7102, 'head': 189, 'tail': 6913}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 3.7037037037037033, 'NDCG@50': 0.856956345036145}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5062924924056126, 'NDCG@50': 0.10219549190129924}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.08154143512925828, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 99.99577583779217, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.2204638801642909, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 98.12869614193185, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower | seed=2 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0646
test_tail_share: 0.9354

counts: {'overall': 7102, 'head': 459, 'tail': 6643}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.7429193899782136, 'NDCG@50': 0.39208688862200586}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5118169501731146, 'NDCG@50': 0.10363906410477382}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.07883565797453002, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 99.96620670233737, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.21528198908429352, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 96.12672486623485, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower | seed=2 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1035
test_tail_share: 0.8965

counts: {'overall': 7102, 'head': 735, 'tail': 6367}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.4965986394557822, 'NDCG@50': 0.330790578307183}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.48688550337678654, 'NDCG@50': 0.09821126270924038}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.07618699335649418, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 99.9647986482681, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.2011336624611446, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 88.2390875809631, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower | seed=2 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2858
test_tail_share: 0.7142

counts: {'overall': 7102, 'head': 2030, 'tail': 5072}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.6748768472906401, 'NDCG@50': 0.3491469319494086}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.15772870662460567, 'NDCG@50': 0.03148144969799163}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.06351626016260162, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 90.03660940580119, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.16831808943089432, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 66.13658124471979, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower | seed=2 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5370
test_tail_share: 0.4630

counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.12228135521339244}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.9963293130571578, 'NDCG@50': 0.20793023223214177}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.12165450121654502, 'NDCG@50': 0.022930741785925888}
[long_tail] {'CatalogCoverage@10': 0.08447729672650475, 'TailCoverage@10': 0.05279831045406547, 'AvgPopularity@10': 2.7131941597785882, 'TailRatio@10': 80.09293156857224, 'Personalization@10': 2.369966573537996, 'CatalogCoverage@50': 0.22326142706290542, 'TailCoverage@50': 0.13576708402473978, 'AvgPopularity@50': 3.4212316038152593, 'TailRatio@50': 44.19262179667699, 'Personalization@50': 1.509719181947744}

================================================================================
TwoTower seed 3
================================================================================

seed 3 epoch 1: train loss = 8.3242

new best val HR@50 = 0.3802

seed 3 epoch 2: train loss = 8.3188

seed 3 epoch 3: train loss = 8.3180

new best val HR@50 = 0.5351

seed 3 epoch 4: train loss = 8.3179

seed 3 epoch 5: train loss = 8.3178

seed 3 epoch 6: train loss = 8.3178

seed 3 epoch 7: train loss = 8.3178

seed 3 epoch 8: train loss = 8.3178

seed 3 epoch 9: train loss = 8.3178

seed 3 epoch 10: train loss = 8.3178

seed 3 epoch 11: train loss = 8.3178

seed 3 epoch 12: train loss = 8.3178

seed 3 epoch 13: train loss = 8.3178

seed 3 epoch 14: train loss = 8.3178

seed 3 epoch 15: train loss = 8.3178

seed 3 epoch 16: train loss = 8.3178

seed 3 epoch 17: train loss = 8.3178

seed 3 epoch 18: train loss = 8.3178

seed 3 epoch 19: train loss = 8.3178

seed 3 epoch 20: train loss = 8.3178

seed 3 best val HR@50: 0.5351

TEST METRICS
counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.101206082852648, 'NDCG@50': 0.24007977616723702}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.02262784733745663, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 59.90002816108139, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.1508523155830442, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 40.74063644043932, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower | seed=3 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0266
test_tail_share: 0.9734

counts: {'overall': 7102, 'head': 189, 'tail': 6913}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 7.936507936507936, 'NDCG@50': 1.552218115317942}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.39056849414147254, 'NDCG@50': 0.09001808802354276}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.042280744141096886, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 99.4607152914672, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.23858419908190384, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 94.39369191776964, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower | seed=3 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0646
test_tail_share: 0.9354

counts: {'overall': 7102, 'head': 459, 'tail': 6643}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 5.010893246187364, 'NDCG@50': 1.0525967997226033}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.2860153545085052, 'NDCG@50': 0.06510948897021934}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.036385688295936934, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 89.73528583497607, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.2304426925409339, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 88.57054350887074, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower | seed=3 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1035
test_tail_share: 0.8965

counts: {'overall': 7102, 'head': 735, 'tail': 6367}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 4.489795918367347, 'NDCG@50': 0.9826845846423407}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.14135385581906706, 'NDCG@50': 0.03037397464892757}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.03352227707685744, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 89.65361869895804, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.21941854086670326, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 82.6192621796677, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower | seed=3 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2858
test_tail_share: 0.7142

counts: {'overall': 7102, 'head': 2030, 'tail': 5072}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.87192118226601, 'NDCG@50': 0.4144816634587645}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.07886435331230283, 'NDCG@50': 0.01464244666414631}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.02858231707317073, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 79.74232610532245, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.18102134146341464, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 66.63728527175444, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower | seed=3 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5370
test_tail_share: 0.4630

counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5913827090960293, 'NDCG@50': 0.128930479625717}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.101206082852648, 'NDCG@50': 0.24007977616723702}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.04525569467491326, 'TailCoverage@10': 0.02262784733745663, 'AvgPopularity@10': 3.204277455952297, 'TailRatio@10': 59.90002816108139, 'Personalization@10': 1.2553516861412817, 'CatalogCoverage@50': 0.24739779755619246, 'TailCoverage@50': 0.1508523155830442, 'AvgPopularity@50': 3.5756219344831606, 'TailRatio@50': 40.74063644043932, 'Personalization@50': 2.056894664349529}

================================================================================
TwoTower seed 4
================================================================================

seed 4 epoch 1: train loss = 8.3242

new best val HR@50 = 0.5632

seed 4 epoch 2: train loss = 8.3186

seed 4 epoch 3: train loss = 8.3182

seed 4 epoch 4: train loss = 8.3179

seed 4 epoch 5: train loss = 8.3179

seed 4 epoch 6: train loss = 8.3178

seed 4 epoch 7: train loss = 8.3178

seed 4 epoch 8: train loss = 8.3178

seed 4 epoch 9: train loss = 8.3178

seed 4 epoch 10: train loss = 8.3178

seed 4 epoch 11: train loss = 8.3178

new best val HR@50 = 0.5773

seed 4 epoch 12: train loss = 8.3178

seed 4 epoch 13: train loss = 8.3178

seed 4 epoch 14: train loss = 8.3178

seed 4 epoch 15: train loss = 8.3178

seed 4 epoch 16: train loss = 8.3178

seed 4 epoch 17: train loss = 8.3178

seed 4 epoch 18: train loss = 8.3178

seed 4 epoch 19: train loss = 8.3178

seed 4 epoch 20: train loss = 8.3178

seed 4 best val HR@50: 0.5773

TEST METRICS
counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.048767697954903, 'NDCG@50': 0.18784333485840574}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.47895610197616534, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 56.98817234581808, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.0974505958666467, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 58.09124190368911, 'Personalization@50': 6.263736438928347}

================================================================================
TwoTower | seed=4 | head_fraction=0.001 (0.100%)
================================================================================
num_head_items: 33
num_tail_items: 33,112
test_head_share: 0.0266
test_tail_share: 0.9734

counts: {'overall': 7102, 'head': 189, 'tail': 6913}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 12.16931216931217, 'NDCG@50': 2.171028216908939}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.24591349631129755, 'NDCG@50': 0.04428036252772605}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.5013288233872916, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 97.15150661785412, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.1476201981154868, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 94.5060546324979, 'Personalization@50': 6.263736438928347}

================================================================================
TwoTower | seed=4 | head_fraction=0.005 (0.500%)
================================================================================
num_head_items: 165
num_tail_items: 32,980
test_head_share: 0.0646
test_tail_share: 0.9354

counts: {'overall': 7102, 'head': 459, 'tail': 6643}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 5.010893246187364, 'NDCG@50': 0.8939527951977984}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.2559084750865573, 'NDCG@50': 0.04608010630049227}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.5033353547604609, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 97.15150661785412, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.1522134627046696, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 94.5060546324979, 'Personalization@50': 6.263736438928347}

================================================================================
TwoTower | seed=4 | head_fraction=0.01 (1.000%)
================================================================================
num_head_items: 331
num_tail_items: 32,814
test_head_share: 0.1035
test_tail_share: 0.8965

counts: {'overall': 7102, 'head': 735, 'tail': 6367}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 3.537414965986395, 'NDCG@50': 0.6310888093628514}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.21988377571854878, 'NDCG@50': 0.039670834658122156}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.5028341561528615, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 96.6192621796677, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.151947339550192, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 92.46043368065334, 'Personalization@50': 6.263736438928347}

================================================================================
TwoTower | seed=4 | head_fraction=0.05 (5.000%)
================================================================================
num_head_items: 1,657
num_tail_items: 31,488
test_head_share: 0.2858
test_tail_share: 0.7142

counts: {'overall': 7102, 'head': 2030, 'tail': 5072}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.7241379310344827, 'NDCG@50': 0.30839464382836934}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.09858044164037855, 'NDCG@50': 0.017822033158195947}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.4795477642276422, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 75.32807659814137, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.1369410569105691, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 72.7105040833568, 'Personalization@50': 6.263736438928347}

================================================================================
TwoTower | seed=4 | head_fraction=0.2 (20.000%)
================================================================================
num_head_items: 6,629
num_tail_items: 26,516
test_head_share: 0.5370
test_tail_share: 0.4630

counts: {'overall': 7102, 'head': 3814, 'tail': 3288}
[overall] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.5632216277105041, 'NDCG@50': 0.10087784837369185}
[head] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 1.048767697954903, 'NDCG@50': 0.18784333485840574}
[tail] {'HR@10': 0.0, 'NDCG@10': 0.0, 'HR@50': 0.0, 'NDCG@50': 0.0}
[long_tail] {'CatalogCoverage@10': 0.5098808266706895, 'TailCoverage@10': 0.47895610197616534, 'AvgPopularity@10': 3.0892006598097437, 'TailRatio@10': 56.98817234581808, 'Personalization@10': 67.81939597752206, 'CatalogCoverage@50': 1.1585457836777795, 'TailCoverage@50': 1.0974505958666467, 'AvgPopularity@50': 3.188902421384942, 'TailRatio@50': 58.09124190368911, 'Personalization@50': 6.263736438928347}

,method,seed,lr,dropout,weight_decay,best_val_HR@50,test_overall_HR@10,test_overall_NDCG@10,test_overall_HR@50,test_overall_NDCG@50,...,test_TailRatio@10,test_Personalization@10,test_CatalogCoverage@50,test_TailCoverage@50,test_AvgPopularity@50,test_TailRatio@50,test_Personalization@50,test_count_overall,test_count_head,test_count_tail
0,TwoTower,0,0.001,0.9,0.001,0.971557,0.422416,0.190222,0.718108,0.259335,...,0.180231,6.434834,0.202142,0.113139,3.547882,41.972965,2.856856,7102,3814,3288
1,TwoTower,1,0.001,0.9,0.001,0.718108,0.239369,0.103350,0.549141,0.173629,...,30.033793,3.304239,0.199125,0.131996,3.354717,44.524078,3.245621,7102,3814,3288
2,TwoTower,2,0.001,0.9,0.001,0.535061,0.000000,0.000000,0.591383,0.122281,...,80.092932,2.369967,0.223261,0.135767,3.421232,44.192622,1.509719,7102,3814,3288
3,TwoTower,3,0.001,0.9,0.001,0.535061,0.000000,0.000000,0.591383,0.128930,...,59.900028,1.255352,0.247398,0.150852,3.575622,40.740636,2.056895,7102,3814,3288
4,TwoTower,4,0.001,0.9,0.001,0.577302,0.000000,0.000000,0.563222,0.100878,...,56.988172,67.819396,1.158546,1.097451,3.188902,58.091242,6.263736,7102,3814,3288

In [12]:
def make_final_summary_table(
    metrics_df: pd.DataFrame,
    sweep_df: pd.DataFrame,
    method_name: str = "TwoTower",
    save_path: str | None = None,
) -> pd.DataFrame:
    """
    Делает одну финальную таблицу mean ± std по seed-ам.

    metrics_df:
        обычные test metrics по seed-ам.
        one row = one seed.

    sweep_df:
        head/tail sweep по seed-ам.
        one row = one seed × one head_fraction.

    Возвращает:
        summary_df:
            one row = one method × one head_fraction.
            Метрики записаны в формате 'mean ± std'.
    """

    if len(sweep_df) == 0:
        raise ValueError("sweep_df is empty")

    # Метрики, которые хотим видеть в финальной таблице
    selected_metrics = [
        "overall_HR@50",
        "overall_NDCG@50",
        "head_HR@50",
        "head_NDCG@50",
        "tail_HR@50",
        "tail_NDCG@50",
        "CatalogCoverage@50",
        "TailCoverage@50",
        "AvgPopularity@50",
        "TailRatio@50",
        "Personalization@50",
    ]

    rows = []

    # groupby по head_fraction: внутри группы разные seeds
    for head_fraction, group in sweep_df.groupby("head_fraction"):
        group = group.copy()

        row = {
            "method": method_name,
            "head_share": f"{100 * float(head_fraction):.3f}%",
            "head_fraction": float(head_fraction),
            "num_seeds": group["seed"].nunique() if "seed" in group.columns else len(group),
            "num_head_items": int(group["num_head_items"].iloc[0]) if "num_head_items" in group.columns else np.nan,
            "num_tail_items": int(group["num_tail_items"].iloc[0]) if "num_tail_items" in group.columns else np.nan,
        }

        if "test_head_share" in group.columns:
            row["test_head_share"] = f"{100 * float(group['test_head_share'].mean()):.2f}%"

        if "test_tail_share" in group.columns:
            row["test_tail_share"] = f"{100 * float(group['test_tail_share'].mean()):.2f}%"

        if metrics_df is not None and len(metrics_df) > 0:
            for hp_col in ["lr", "dropout", "weight_decay", "logq_weight", "cb_beta"]:
                if hp_col in metrics_df.columns:
                    vals = metrics_df[hp_col].dropna().unique()
                    if len(vals) == 1:
                        row[hp_col] = vals[0]
                    elif len(vals) > 1:
                        row[hp_col] = ", ".join(map(str, vals))

            if "best_val_HR@50" in metrics_df.columns:
                vals = metrics_df["best_val_HR@50"].dropna().to_numpy(dtype=float)
                if len(vals) > 0:
                    mean = float(np.mean(vals))
                    std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
                    row["best_val_HR@50"] = f"{mean:.2f} ± {std:.2f}"

        for metric in selected_metrics:
            if metric not in group.columns:
                continue

            vals = group[metric].dropna().to_numpy(dtype=float)

            if len(vals) == 0:
                row[metric] = "nan"
                continue

            mean = float(np.mean(vals))
            std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0

            if "AvgPopularity" in metric:
                row[metric] = f"{mean:.4f} ± {std:.4f}"
            else:
                row[metric] = f"{mean:.2f} ± {std:.2f}"

        rows.append(row)

    summary_df = pd.DataFrame(rows).sort_values("head_fraction").reset_index(drop=True)

    first_cols = [
        "method",
        "head_share",
        "head_fraction",
        "num_seeds",
        "num_head_items",
        "num_tail_items",
        "test_head_share",
        "test_tail_share",
        "lr",
        "dropout",
        "weight_decay",
        "logq_weight",
        "cb_beta",
        "best_val_HR@50",
    ]

    metric_cols = [
        "overall_HR@50",
        "overall_NDCG@50",
        "head_HR@50",
        "head_NDCG@50",
        "tail_HR@50",
        "tail_NDCG@50",
        "CatalogCoverage@50",
        "TailCoverage@50",
        "AvgPopularity@50",
        "TailRatio@50",
        "Personalization@50",
    ]

    ordered_cols = [
        c for c in first_cols + metric_cols
        if c in summary_df.columns
    ]

    other_cols = [
        c for c in summary_df.columns
        if c not in ordered_cols
    ]

    summary_df = summary_df[ordered_cols + other_cols]

    if save_path is not None:
        summary_df.to_csv(save_path, index=False)
        print(f"saved: {save_path}")

    return summary_df

In [13]:
summary_df = make_final_summary_table(metrics_df, sweep_df, save_path="yambda_twotower_summary.csv")

saved: yambda_twotower_summary.csv

In [14]:
summary_df

,method,head_share,head_fraction,num_seeds,num_head_items,num_tail_items,test_head_share,test_tail_share,lr,dropout,...,overall_NDCG@50,head_HR@50,head_NDCG@50,tail_HR@50,tail_NDCG@50,CatalogCoverage@50,TailCoverage@50,AvgPopularity@50,TailRatio@50,Personalization@50
0,TwoTower,0.100%,0.001,5,33,33112,2.66%,97.34%,0.001,0.9,...,0.16 ± 0.06,10.05 ± 4.92,2.90 ± 2.09,0.34 ± 0.11,0.08 ± 0.02,0.41 ± 0.42,0.40 ± 0.42,3.4177 ± 0.1567,94.82 ± 2.77,3.19 ± 1.85
1,TwoTower,0.500%,0.005,5,165,32980,6.46%,93.54%,0.001,0.9,...,0.16 ± 0.06,4.84 ± 2.25,1.38 ± 0.95,0.31 ± 0.12,0.07 ± 0.02,0.41 ± 0.42,0.39 ± 0.42,3.4177 ± 0.1567,91.72 ± 4.77,3.19 ± 1.85
2,TwoTower,1.000%,0.010,5,331,32814,10.35%,89.65%,0.001,0.9,...,0.16 ± 0.06,3.48 ± 1.45,0.96 ± 0.55,0.27 ± 0.13,0.06 ± 0.03,0.41 ± 0.42,0.39 ± 0.43,3.4177 ± 0.1567,87.99 ± 4.59,3.19 ± 1.85
3,TwoTower,5.000%,0.050,5,1657,31488,28.58%,71.42%,0.001,0.9,...,0.16 ± 0.06,1.78 ± 0.26,0.48 ± 0.20,0.13 ± 0.04,0.03 ± 0.01,0.41 ± 0.42,0.36 ± 0.43,3.4177 ± 0.1567,70.87 ± 4.16,3.19 ± 1.85
4,TwoTower,20.000%,0.200,5,6629,26516,53.70%,46.30%,0.001,0.9,...,0.16 ± 0.06,1.09 ± 0.15,0.29 ± 0.12,0.04 ± 0.06,0.01 ± 0.01,0.41 ± 0.42,0.33 ± 0.43,3.4177 ± 0.1567,45.90 ± 6.99,3.19 ± 1.85